config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration' },
             controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
    end
    resources :photos, only: %i[create destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true

  def cover_photo(size)
    if !photos.empty?
      photos[0].image.url(size)
    else
      'blank.png'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :omniauthable

  validates :fullname, presence: true, length: { maximum: 50 }

  has_many :rooms

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else

      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.fullname = auth.info.name
        user.image = auth.info.image
        user.uid = auth.uid
        user.provider = auth.provider
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end

    end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[fullname phone_number description])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
        @room.photos.create(image: img)
      end
      @photos = @room.photos
      redirect_back(fallback_location: request.referer, notice: 'Saved...')
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: @room.id)

    respond_to :js
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: %i[index new create]
  before_action :authenticate_user!, excep: [:show]
  before_action :is_authorised, only: %i[listing pricing description photo_upload amenities location update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to listing_room_path(@room), notice: 'Saved...'
    else
      flash[:alert] = 'Something went wrong'
      render :new
    end
  end

  def show; end

  def listing; end

  def pricing; end

  def description; end

  def photo_upload
    @photos = @room.photos
  end

  def amenities; end

  def location; end

  def update
    new_params = room_params

    new params = room_params.merge(active: true) if is_ready_room

    if @room.update(new_params)
      flash[:notice] = 'Saved...'
    else
      flash[:alert] = 'Something went wrong...'
     end
    redirect_back(fallback_location: request.referer)
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def is_ready_room
    !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
  end

  def is_authorised
    redirect_to root_path, alert: 'You do not have permission' unless current_user.id == @room.user_id
  end

  def room_params
    params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room, :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_heating, :is_internet, :price, :active)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def start
    render 'welcome'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_url(user)
    if user.image
      "http://graph.facebook.com/#{user.uid}/picture?type=large"
    else
      gravatar_id = Digest::MD5.hexdigest(user.email).downcase
      "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?=identical&s=150"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirPikachu</title>

    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  </head>

  <body>

    <%= render 'shared/navbar' %>
    <%= render 'shared/message' %>

    <div class="container">
        <%= yield %>
    </div>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/photos/_photos_list.html.erb
<% if @photos.count > 0 %>
  <br><br>

  <div class="row container-photos-uploaded">
      <% @photos.each do |photo| %>
      <div class="col-md-4 container-photo">
           <%= image_tag photo.image.url(), class: 'img-fluid' %>
            <span class="pull-right">
              <%= link_to "<i class='fa fa-trash-o' aria-hidden='true'> </i>".html_safe, room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure"} %>
            </span>
      </div>
    <%end%>
  </div>
<%end%>

app/views/photos/destroy.js.erb
$("#photos").html("<%= j render 'photos_list' %>")

<% if @room.photos.blank? %>
  $('#photo-check').hide();
<%end%>

<% if !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?%>
    $('#publish-button').attr('disabled', false);
<%else%>
    $('#publish-button').attr('disabled', true  );
<%end%>

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-list">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class='float-right text-babu'><i class='fa fa-check'></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
     <% if !@room.price.blank? %>
      <span class='float-right text-babu'><i class='fa fa-check'></i></span>
      <%end%>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
     <span class='float-right text-babu'><i class='fa fa-check'></i></span>
     <%end%>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank? %>
     <span id='photo-check' class='float-right text-babu'><i class='fa fa-check'></i></span>
     <%end%>
  </li>
  <li class="sidebar-item">

    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
      <span class='float-right text-babu'><i class='fa fa-check'></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
     <span class='float-right text-babu'><i class='fa fa-check'></i></span>
     <%end%>
  </li>

</ul>
<hr>
<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>
<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value:true %>
  <%= f.submit "Publish", id: "publish-button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<%end%>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Amenities</h4>
        <div class='row'>
          <%= form_for @room do |f| %>
              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_tv %> TV
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_kitchen %> Kitchen
                </div>

                <div class="col-md-4">
                  <%= f.check_box :is_internet %> Internet
                </div>
              </div>
              <div class="row form-group">
                <div class="col-md-4">
                  <%= f.check_box :is_heating %> Heating
                </div>
                <div class="col-md-4">
                  <%= f.check_box :is_air %> Air Conditioning
                </div>
              </div>

              <div class="text-center">
                <%= f.submit "Save", class:"btn btn-form" %>
              </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Description</h4>
        <div>
          <%= form_for @room do |f| %>
          <div class="row form-group">
            <label>Listing name</label>
            <%= f.text_field :listing_name, placeholder: "What is your listing name", class: "form-control", required: true %>
          </div>

          <div class="row form-group">
            <label>Summary</label>
            <%= f.text_area :summary, id:"description-text-area" , placeholder: "Summary of your home", class: "form-control", required: true %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item">
        <%= link_to "Your Listings", rooms_path, class: 'sidebar-link active' %> </li>
        <%= link_to "Your Reservations", rooms_path, class: 'sidebar-link active' %> </li>
      </li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="card" >
      <div class="card-block">
        <h5 class="card-title">Listings</h5>
        <% @rooms.each do |room | %>
            <div class="d-flex flex-row justify-content-between align-content-center align-items-start">
              <div class='ml-3'>
                <%= image_tag room.cover_photo(:thumb)%>
              </div>
              <h6 class='mr-auto pl-4'><%= room.listing_name %></h6>
              <div class='pr-4'>
                <%= link_to 'Update', listing_room_path(room), class: 'btn btn-form' %>
              </div>
          </div>
          <hr>
        <%end%>
      </div>
    </div>

  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Listing</h4>
        <div>
          <%= form_for @room do |f| %>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group select">
                <label>Home type</label>
                <%= f.select :home_type, [["Apartment", "Apartment"],["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                         {prompt: "Select..."}, {class: "form-control", id: "home_type"} %>
              </div>
            </div>

            <div class="col-md-4">

              <div class="form-group select">
                <label>Room type</label>
                <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                          {prompt: "Select..."}, {class: "form-control", id: "room_type"}  %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group select">
                <label>Accomodate</label>
                <%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                           {prompt: "Select..."}, {class: "form-control", id: "accommodate"}  %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group select">
                <label>Bedrooms</label>
                <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                        {prompt: "Select..."}, {class: "form-control", id: "bed_room"}  %>
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group select">
                <label>Bathrooms</label>
                <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                          {prompt: "Select..."}, {class: "form-control", id: "bath_room"}  %>
              </div>
            </div>


          </div>

          <div class='text-center'>
                <%= f.submit "Save", class:"btn btn-form" %>
          </div>

          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Location</h4>
        <div>
          <%= form_for @room do |f| %>

            <div class="form-group">
              <label>Address</label>
              <%= f.text_field :address, placeholder: "What is your address", class: "form-control", required: true %>
            </div>

            <div class="form-group text-center">

              <%= f.submit "Save", class: "btn btn-form" %>
            </div>

          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<!-- <div class="col-md-12"> -->
<div class="card">
  <div class="card-block">
    <h4 class="card-title">Create your beautiful place</h4>
    <%=  form_for @room do |f| %>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label>Home type</label>
            <%= f.select :home_type, [["Apartment", "Apartment"],["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                     {prompt: "Select..."}, {class: "form-control", id: "home_type"} %>
          </div>
        </div>

        <div class="col-md-4">

          <div class="form-group">
            <label>Room type</label>
            <%= f.select :room_type, [["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                      {prompt: "Select..."}, {class: "form-control", id: "room_type"}  %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <label>Accomodate</label>
            <%= f.select :accomodate, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                       {prompt: "Select..."}, {class: "form-control", id: "accommodate"}  %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <label>Bedrooms</label>
            <%= f.select :bed_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                    {prompt: "Select..."}, {class: "form-control", id: "bed_room"}  %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <label>Bathrooms</label>
            <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                      {prompt: "Select..."}, {class: "form-control", id: "bath_room"}  %>
          </div>
        </div>

      </div>

      <div class='text-center'>
          <%= f.submit "Create my room", class:"btn btn-normal" %>
      </div>


    <% end %>

  </div>
</div>
<!-- </div> -->

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Photos</h4>
        <div>
          <%=  form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f|  %>
            <div class="row justify-content-center">
              <div class="form-group col-md-6 ">
                <span class="btn btn-default btn-file text-babu">
                  Select photos
                  <%= file_field_tag "images[]", type: :file, multiple: true %>
                </span>
              </div>
            </div>

          <div class="text-center">
            <%= f.submit "Add photos", class:"btn btn-form" %>
          </div>
          <% end %>
        </div>
    </div>
      <div id="photos">
        <%= render 'photos/photos_list' %>
      </div>
   </div>
  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>
  <div class="col-md-9">
    <div class="card">
      <div class="card-block">
        <h4 class="card-title">Pricing</h4>
        <div>
          <%= form_for @room do |f| %>
          <div class="form-group">
            <label>Price</label>
            <%= f.text_field :price, placeholder: "eg. $100", class:'form-control', required: true %>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Save", class: "btn btn-form" %>
          </div>

          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= image_tag @room.cover_photo(nil), width: '100%' %>
  </div>
</div>
<br>

<div class="row">
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-8">
        <h1><%= @room.listing_name %></h1>
        <%= @room.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@room.user), class: 'rounded-circle avatar_medium' %> <br><br>
        <%= @room.user.fullname %>
      </div>
  </div>

  <hr>

    <div class="row d-flex flex-row justify-content-between text-babu">

        <div class="col-md-3 text-center">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3 text-center">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3 text-center">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3 text-center">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>

      <div class="row d-flex flex-row justify-content-between text-babu">
        <div class="col-md-3 text-center"><%=@room.home_type %></div>
        <div class="col-md-3 text-center"><%=pluralize(@room.accomodate, 'Guest') %></div>
        <div class="col-md-3 text-center"><%=pluralize(@room.bed_room, 'Bedroom')%></div>
        <div class="col-md-3 text-center"><%=pluralize(@room.accomodate, 'Bathroom')%></div>
      </div>
      <hr>

      <div class="row">
        <div class="col-md-12 mt-4">
          <h3>About this listing</h3>
          <p><%= @room.summary %></p>
        </div>
    </div>
    <hr>

    <div class="row">
      <div class="col-md-3">
        <h4 class='pt-3'>Amenities</h4>
      </div>
      <div class="col-md-9">
        <div class='row'>
          <div class="col-md-6">
            <ul class="amenities">
              <li class='<%= 'text-line-through' if !@room.is_tv %>'>TV</li>
              <li>kitchen</li>
              <li>Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li>Heating</li>
              <li>Air conditioning</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    </div>

    <div class="row">
      <hr>
    </div>
  </div>

  <div class="col-md-4">

  </div>
</div>
</div>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
  <script type='text/javascript'>
    <% resource.errors.full_messages.each do | value | %>
        toastr.error('<%= value %>')
    <%end%>
  </script>
<%end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
  <script type='text/javascript'>
    <% flash.each do | key, value | %>
        <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
        toastr['<%= type %>']('<%= value %>')
    <%end%>
  </script>
<%end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">AirPikachu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">

        <% if (!user_signed_in?) %>
        <li class="nav-item active">
          <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Sign Up', new_user_registration_path,  class: 'nav-link' %>
        </li>
        <%else %>

        <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= image_tag avatar_url(current_user), class: 'img-fluid rounded-circle avatar_medium' %>&nbsp
                <%= current_user.fullname %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="#">Manage listings</a>
                <a class="dropdown-item" href="#">List your space</a>
                <a class="dropdown-item" href="#">Your reservations</a>
                <a class="dropdown-item" href="#">Your trips</a>
                <div class="dropdown-divider"></div>
                <a><%= link_to 'Edit profile', edit_user_registration_path, class: 'dropdown-item' %></a>
                <a><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item' %></a>
              </div>
            </li>
        <%end %>
      </ul>
  </div>
</nav>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-3">
<div class="card" >
  <%= image_tag avatar_url(@user), class: 'avatar-full' %>
  <div class="card-block">
    <h5 class="card-title">Verification</h5>
    <p class="card-text">Email Address: <br> <small><%= @user.email %></small> </p>
    <hr>
    <p class="card-text">Phone Number: <br> <small><%= @user.phone_number %></small></p>
  </div>
</div>
  </div>

  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>

    <div class="description row-space-3">
      <%= @user.description %>
    </div>
  </div>
</div>